apiVersion: v1
kind: Service

metadata:
  name: tripforge-api
  namespace: tripforge

spec:
  selector:
    app: tripforge-api

  ports:
    - port: 8000
      targetPort: 8000

  type: ClusterIP