apiVersion: apps/v1
kind: Deployment

metadata:
  name: tripforge-api
  namespace: tripforge

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: tripforge-api

  template:
    metadata:
      labels:
        app: tripforge-api

    spec:
      containers:
        - name: tripforge-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8000

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: DATABASE_URL
              value: "postgresql+psycopg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
