apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: tripforge

type: Opaque

stringData:
  POSTGRES_USER: tripforge
  POSTGRES_PASSWORD: tripforge_dev
  POSTGRES_DB: tripforge
