apiVersion: v1
kind: Service

metadata:
  name: tripforge-api
  namespace: tripforge

spec:
  selector:
    app: wrong-app

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000

  type: {{ .Values.service.type }}
